[build.environment]
  YARN_VERSION = "1.22.22"
  NODE_VERSION = "20"
  HUGO_VERSION = "0.124.1"
  HUGO_EXTENDED = "true"

[build]
  command = "hugo --gc --minify -s site"
  publish = "site/public"
  functions = "./site/functions"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
