[build.environment]
  YARN_VERSION = "1.22.22"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"
  functions = "./site/functions"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
